### ISSUE TITLE
Using ${hybris.version} is not possible

### ISSUE THREAD

**Issue by StefanKruk** [SAP/commerce-gradle-plugin#19]
We are currently trying to implement the Gradle Plugin for our Setup and facing the Issue that the Variable "hybris.version" cannot be used.

**Gradle Script:**
```
plugins {
    id "sap.commerce.build" version "3.0.0"
    id "sap.commerce.build.ccv2" version "3.0.0"
}

hybris {
    // hybris version to use
    // is preconfigured with commerceSuiteVersion of the manifest
    version = "2005.5"
}

task printVersion {
  println "version: ${hybris.version}"
}
```

**Result:**
`version: extension 'hybris' property 'version'`

**expected:**
`version: 2005.5`

**workaround**
use `${hybris.version.get()}`

**Comment by mpern** [comment]
Thanks for your feedback!

That's actually a feature, I tried to follow Gradle plugin best practices by using lazy properties ([documentation][lazy]) across the board.

Do you have a specific use case where you run into trouble? Maybe we can figure out a workaround together

[lazy]: https://docs.gradle.org/current/userguide/lazy_configuration.html
