### ISSUE TITLE
CCv2 Plugin should support Cloud Integration Extension Pack

### ISSUE THREAD

**Issue by guiliguili** [SAP/commerce-gradle-plugin#21]
As of SAP Commerce 2005, [Cloud Extension Pack](https://help.sap.com/viewer/d352a456045d4e12b5d1b9c80bcf4be3/v1905/en-US) have been replaced by [Cloud Integration Extension Pack](https://help.sap.com/viewer/product/SAP_COMMERCE_INTEGRATIONS/2005/en-US?expandAll=true).

Currently the CCv2 plugin only supports Cloud Extension Pack and should also support Cloud Integration Extension Pack.

**Comment by mpern** [comment]
Thank you for your feedback!

The plugin already supports the `extensionPacks` element of the `manifest.json` file for exactly that purpose, see the release notes for [v2.1.0](https://github.com/SAP/commerce-gradle-plugin/releases/tag/v2.1.0) and the offical documentation on how to deploy the integration extension pack in the cloud ([link](https://help.sap.com/viewer/2f43049ad8e443249e1981575adddb5d/LATEST/en-US/19bacaecbdd34cc8bd58bdd8daf428c5.html))

I haven't updated the plugin documentation though, so no wonder you've missed it.

**Comment by mpern** [comment]
Updated ccv2 plugin documentation with details about `extensionPacks` support
