### ISSUE TITLE
Support for SAP Commerce 2105

### ISSUE THREAD

**Issue by tklostermannNSD** [SAP/commerce-gradle-plugin#36]
Hello, I really like your plugin and want to use it for a new project, but unfortunately in your IntExtPackValidator there are the new sap commerce version 2105 and the new int ext pack version 2108 missing. Can you please add them?
I tried to open a Pull Request, but I don't have permissions for this.

**Comment by mpern** [comment]
Thank you for your kind words!

Regarding Pull Requests:
You should be able to open a PR from a fork. (refer to [Contributing Code Changes](https://github.com/SAP/commerce-gradle-plugin/blob/main/CONTRIBUTING.md#contributing-code-changes) for details)

If this doesn't work anymore, please let me know.

**Comment by tklostermannNSD** [comment]
I opened a PR, thanks :)

**Comment by mpern** [comment]
implemented in #38

Thanks again!
