### ISSUE TITLE
HybrisAntTask xPath error in new SAP commerce version 2205

### ISSUE THREAD

**Issue by tklostermannNSD** [SAP/commerce-gradle-plugin#39]
The hybris ant task throws the error `java.lang.IllegalAccessError: class com.oopsconsultancy.xmltask.jdk15.XPathAnalyser15 (in unnamed module @0x67f946c3) cannot access class com.sun.org.apache.xpath.internal.XPathAPI (in module java.xml) because module java.xml does not export com.sun.org.apache.xpath.internal to unnamed module @0x67f946c3` when trying to install addons with the new version 2205. In fact every ant task that uses the "xmltask" task gets this error.
When trying to install the addon the old way with ". ./setantenv.sh" and "ant addoninstall" command everything works.

These are the added ANT_OPTS in setantenv.sh:
-Dpolyglot.js.nashorn-compat=true -Dpolyglot.engine.WarnInterpreterOnly=false \
--add-exports java.xml/com.sun.org.apache.xpath.internal=ALL-UNNAMED \
--add-exports java.xml/com.sun.org.apache.xpath.internal.objects=ALL-UNNAMED

**Comment by tklostermannNSD** [comment]
I see that ant gets called with these arguments. Then its probably the Java version used for the addoninstall task. This might get fixed by editing the build.gradle with this:
`java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}`

**Comment by tklostermannNSD** [comment]
See https://github.com/SAP/commerce-gradle-plugin/pull/40

**Comment by mpern** [comment]
Thanks for reporting!

The plugin calls ant as an external java executable via Gradles's JavaExec

For 2205, we need to translate the new ANT_OPTS of setantenv.sh to jvmArgs, systemProperties or args as required

**Comment by mpern** [comment]
Fixed in v3.7.0
