### ISSUE TITLE
Gradle 8 support

### ISSUE THREAD

**Issue by mpern** [SAP/commerce-gradle-plugin#45]
Follow up to this PR discussion:

https://github.com/SAP/commerce-gradle-plugin/pull/43#discussion_r1110988719

Gradle 8 seems to have new validation rules regarding Properties and related annotations?

https://docs.gradle.org/8.0.1/userguide/upgrading_version_7.html#changes_8.0.1

**Comment by iccaprar** [comment]
I can take a look at this one.

**Comment by mpern** [comment]
will be solved with #46
