### ISSUE TITLE
Spring Cleaning 2023

### ISSUE THREAD

**Issue by mpern** [SAP/commerce-gradle-plugin#46]
- [x] Update GH Actions to latest versions
- [x] Update Gradle
- [x] Update Gradle Plugins
    - [x] nice-to-have: Use [Test Suite Plugin](https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html#jvm_test_suite_plugin) to define `integrationTest`, `functionalTest`
- [x] Java 17 -> drop support for all Gradle versions < 7.6
- [x] Update build script: use use kotlin script
- [x] Split codebase into subprojects:
    - ~~[ ] platform utils~~
    - [x] test utils (replaces `commonTest` source set)
    - [x] build plugin
    - [x] ccv2 plugin
- [x] remove ccv1 plugin

**Comment by tklostermannNSD** [comment]
Suggestion:

- [ ] Update default-Value for "cleanGlob" to "glob:**hybris/bin/{modules**,platform**}"
