### ISSUE TITLE
sap.commerce.build 3.9.0 not compatible with 2211.7 (FP1)

### ISSUE THREAD

**Issue by andreasschnurbusch** [SAP/commerce-gradle-plugin#48]
The sap.commerce.build fails to invoke ant-tasks when using the latest sap commerce version 2211.7.

The version 2211.6 uses the version number "version=2211.6" in bin/platform/build.number
The version 2211.7 uses "version=2211.FP1". The "FP1" gets converted to a number and fails the build.

error message `for input string "FP1"`

**Comment by mpern** [comment]
Thanks for raising the issue!

You're right, the current parsing doesnt account for `FPn` yet.
Plus, wie also need a way to map .FP1 to .7

**Comment by lennartjuette** [comment]
The issue occurred in our builds, too. Confirmed!

I guess the workaround for now is to stick to 2211.6?

**Comment by lennartjuette** [comment]
Why would the mapping of FP1 to 7 be required? I'm not even trying to ask why they inserted FP1 here and if there will ever be a FP2.

I'm wondering if it even makes sense to map or change anything.

According to [SAP's What's New](https://help.sap.com/docs/SAP_COMMERCE_CLOUD_PUBLIC_CLOUD/251a1313585a498eb998c2f974f4f338/4992e67e47424245ad04444ca6c8d1ca.html) page 2211.7 is a feature preview (FP) release, which will not be available for download anymore, after the next regular patch 2211.8 comes out.

So wouldn't it be enough to be able to cope with FPx versions, which seem to be ephemeral, but not try to really support them any further? Or are you thinking about any cases where version numbers need to be compared to one another, and the FPx needs to be in the right place?

**Comment by mpern** [comment]
> So wouldn't it be enough to be able to cope with FPx versions, which seem to be ephemeral, but not try to really support them any further? 

You have a point!

> Or are you thinking about any cases where version numbers need to be compared to one another, and the FPx needs to be in the right place?

I'm thinking about the manifest.json and the Maven coordinates of preview versions.


But I agee, let's cross that bridge once we get there.

P.S. yes, there will be more feature previews in the future.

**Comment by mpern** [comment]
release with 3.9.1
