### ISSUE TITLE
Sparse build slow when building smartedittools

### ISSUE THREAD

**Issue by iccaprar** [SAP/commerce-gradle-plugin#49]
When building smartedittools `smartedittools.only.build.once=false`, the discovery of existing extensions in the project folder slows a lot (from a few seconds to minutes), because it scans for `extensioninfo.xml` files in all the `node_modules` folders.

**Comment by iccaprar** [comment]
The message logged in info level:
`
Loaded extensions information from project custom folder in T ms
`

where T jumps from 1000-2000 to 50k-150k.

**Comment by mpern** [comment]
Fixes by #50

**Comment by mpern** [comment]
released with 3.9.1
