### ISSUE TITLE
Error with default excludes and gradle >= 6.7

### ISSUE THREAD

**Issue by tklostermannNSD** [SAP/commerce-gradle-plugin#52]
Hi,

the removeUnusedExtensions task seems to be not working with gradle >=6.7:
`Cannot change default excludes during the build. They were changed from [**/#*#, **/%*%, **/*~, **/.#*, **/.DS_Store, **/._*, **/.bzr, **/.bzr/**, **/.bzrignore, **/.cvsignore, **/.git, **/.git/**, **/.gitattributes, **/.gitignore, **/.gitmodules, **/.hg, **/.hg/**, **/.hgignore, **/.hgsub, **/.hgsubstate, **/.hgtags, **/.svn, **/.svn/**, **/CVS, **/CVS/**, **/SCCS, **/SCCS/**, **/vssver.scc] to []. Configure default excludes in the settings script instead.`

Here is the changelog for this:
https://docs.gradle.org/current/userguide/upgrading_version_6.html#changing_default_excludes_during_the_execution_phase

**Comment by mpern** [comment]
Hey!

thanks for the report. I'm tempted to remove `removeUnusedExtensions`, since `sparseBootstrap` is the better solution to the problem.

What do you think?
