### ISSUE TITLE
HybrisAntTask.setMain() fails for yclean

### ISSUE THREAD

**Issue by alanktwong** [SAP/commerce-gradle-plugin#59]
I am trying to use your plugin to setup Commerce 2211 using Gradle 8.2.1 and Java 17

I noticed this failed
> * What went wrong: Execution failed for task ':yclean'.
> Failed to notify task execution listener.
> 'org.gradle.api.tasks.JavaExec mpern.sap.commerce.build.tasks.HybrisAntTask.setMain(java.lang.String)'

And that's due to the fact that Gradle is migrating many tasks over to `Property<String>`. Specifically `getMainClass().set(string)` should be used instead.

https://docs.gradle.org/8.2.1/javadoc/org/gradle/process/JavaExecSpec.html#setMain-java.lang.String-

More precisely, we're using SAP's Gradle plugin and extending it to support the functionality that we want for our proprietary plugin.

**Comment by mpern** [comment]
Hi Alan!

I cannot reproduce the issue using a sample test project.
Are you configuring/modifying the `yclean` task in your build somehow?

**Comment by alanktwong** [comment]
@mpern ,
No problems.  I found the root cause, which was I had a `buildSrc/build.gradle` trying to download an older version of the plugin that was using JavaExecSpec.setMain(...), when my build.gradle was using the newer version.

So if others run into the issue the solution is simple:
* If you don't need commerce-gradle-plugin in buildSrc, remove it.
* If you do need commerce-gradle-plugin in buildSrc, make sure it is the same version as the one you use in the parent build.gradle. Ideally you can just look the required version in your project's `gradle.properties`.

**Comment by alanktwong** [comment]
This issue can be closed.

**Comment by mpern** [comment]
https://docs.gradle.org/current/userguide/custom_plugins.html#applying_external_plugins_in_precompiled_script_plugins
